const std = @import("std");
const load_image_mod = @import("Extract/load_image.zig");
const extract_mod = @import("Extract/extract.zig");
const hct_mod = @import("Hct/Hct.zig");
const stringUtils_mod = @import("Utils/StringUtils.zig");
const temperature_mod = @import("Temperature/TemperatureCache.zig");
const schemeContent_mod = @import("Scheme/SchemeContent.zig");
const schemeExpressive_mod = @import("Scheme/SchemeExpressive.zig");
const schemeFidelity_mod = @import("Scheme/SchemeFidelity.zig");
const schemeFruitSalad_mod = @import("Scheme/SchemeFruitSalad.zig");
const schemeMonoChrome_mod = @import("Scheme/SchemeMonoChrome.zig");
const schemeNeutral_mod = @import("Scheme/SchemeNeutral.zig");
const schemeRainbow_mod = @import("Scheme/SchemeRainbow.zig");
const schemeTonalSpot_mod = @import("Scheme/SchemeTonalSpot.zig");
const schemeVibrant_mod = @import("Scheme/SchemeVibrant.zig");
const dynamicScheme_mod = @import("DynamicColor/DynamicScheme.zig");
const temperatureCache = temperature_mod.TemperatureCache;
const loadImageSubsample = load_image_mod.loadImageSubsample;
const extract = extract_mod.extract;
const hexFromArgb = stringUtils_mod.hexFromArgb;
const fromInt = hct_mod.fromInt;
const schemeContent = schemeContent_mod.schemeContent;
const schemeExpressive = schemeExpressive_mod.schemeExpressive;
const schemeFidelity = schemeFidelity_mod.schemeFidelity;
const schemeFruitSalad = schemeFruitSalad_mod.schemeFruitSalad;
const schemeMonoChrome = schemeMonoChrome_mod.schemeMonoChrome;
const schemeNeutral = schemeNeutral_mod.schemeNeutral;
const schemeRainbow = schemeRainbow_mod.schemeRainbow;
const schemeTonalSpot = schemeTonalSpot_mod.schemeTonalSpot;
const schemeVibrant = schemeVibrant_mod.schemeVibrant;
const showAllColors = dynamicScheme_mod.showAllColors;

var threaded: std.Io.Threaded = .init_single_threaded;
const io = threaded.io();

// const Timer = std.time.Timer;

pub fn main() !void {
    // const args_c_style = std.os.argv;
    // if (args_c_style.len != 2) {
    //     std.debug.print("Usage: {s} <image_path>", .{std.mem.span(args_c_style[0])});
    //     return;
    // }
    // const image_path: [*:0]const u8 = std.mem.span(args_c_style[1]);
    var stdout_writer = std.Io.File.stdout().writer(io, &.{});
    const stdout = &stdout_writer.interface;
    // var rgb: [60000]u8 = undefined;
    // var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    // defer arena.deinit();
    // const allocator = arena.allocator();
    // const out_count = try loadImageSubsample(allocator, &rgb, image_path);
    // try stdout.print("Extract colors from {s}\n", .{image_path});
    // // var timer = try Timer.start();
    // const extracted_colors = extract(128, rgb[0 .. out_count * 3], 4);
    // // const time = timer.read();
    // // try stdout.print("Extraction took {d} ms\n", .{time / std.time.ns_per_ms});
    // try stdout.print("Extracted 4 Colors:\n", .{});
    // for (extracted_colors) |color| {
    //     try stdout.print("{s}\n", .{hexFromArgb(color)});
    // }
    // try stdout.print("Use source color {s} to create scheme\n", .{hexFromArgb(extracted_colors[0])});
    // const color = fromInt(extracted_colors[0]);
    const color = fromInt(0x2762cf);
    const cache = temperatureCache.make(color);
    const contentLight = schemeContent(color, false, 0.0, cache);
    const contentDark = schemeContent(color, true, 0.0, cache);
    const expressiveLight = schemeExpressive(color, false, 0.0);
    const expressiveDark = schemeExpressive(color, true, 0.0);
    const fidelityLight = schemeFidelity(color, false, 0.0, cache);
    const fidelityDark = schemeFidelity(color, true, 0.0, cache);
    const fruitSaladLight = schemeFruitSalad(color, false, 0.0);
    const fruitSaladDark = schemeFruitSalad(color, true, 0.0);
    const monoChromeLight = schemeMonoChrome(color, false, 0.0);
    const monoChromeDark = schemeMonoChrome(color, true, 0.0);
    const neutralLight = schemeNeutral(color, false, 0.0);
    const neutralDark = schemeNeutral(color, true, 0.0);
    const rainbowLight = schemeRainbow(color, false, 0.0);
    const rainbowDark = schemeRainbow(color, true, 0.0);
    const tonalSpotLight = schemeTonalSpot(color, false, 0.0);
    const tonalSpotDark = schemeTonalSpot(color, true, 0.0);
    const vibrantLight = schemeVibrant(color, false, 0.0);
    const vibrantDark = schemeVibrant(color, true, 0.0);
    try stdout.print("\nScheme Content Light:\n", .{});
    try showAllColors(stdout, contentLight);
    try stdout.print("\nScheme Content Dark:\n", .{});
    try showAllColors(stdout, contentDark);
    try stdout.print("\nScheme Expressive Light:\n", .{});
    try showAllColors(stdout, expressiveLight);
    try stdout.print("\nScheme Expressive Dark:\n", .{});
    try showAllColors(stdout, expressiveDark);
    try stdout.print("\nScheme Fidelity Light:\n", .{});
    try showAllColors(stdout, fidelityLight);
    try stdout.print("\nScheme Fidelity Dark:\n", .{});
    try showAllColors(stdout, fidelityDark);
    try stdout.print("\nScheme FruitSalad Light:\n", .{});
    try showAllColors(stdout, fruitSaladLight);
    try stdout.print("\nScheme FruitSalad Dark:\n", .{});
    try showAllColors(stdout, fruitSaladDark);
    try stdout.print("\nScheme MonoChrome Light:\n", .{});
    try showAllColors(stdout, monoChromeLight);
    try stdout.print("\nScheme MonoChrome Dark:\n", .{});
    try showAllColors(stdout, monoChromeDark);
    try stdout.print("\nScheme Neutral Light:\n", .{});
    try showAllColors(stdout, neutralLight);
    try stdout.print("\nScheme Neutral Dark:\n", .{});
    try showAllColors(stdout, neutralDark);
    try stdout.print("\nScheme Rainbow Light:\n", .{});
    try showAllColors(stdout, rainbowLight);
    try stdout.print("\nScheme Rainbow Dark:\n", .{});
    try showAllColors(stdout, rainbowDark);
    try stdout.print("\nScheme TonalSpot Light:\n", .{});
    try showAllColors(stdout, tonalSpotLight);
    try stdout.print("\nScheme TonalSpot Dark:\n", .{});
    try showAllColors(stdout, tonalSpotDark);
    try stdout.print("\nScheme Vibrant Light:\n", .{});
    try showAllColors(stdout, vibrantLight);
    try stdout.print("\nScheme Vibrant Dark:\n", .{});
    try showAllColors(stdout, vibrantDark);
}
