name: Lean + Futhark + ISPC CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout
      - uses: actions/checkout@v5

      # 2. 安装 clang（ubuntu-latest 不保证有 clang）
      - name: Install clang
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      # 3. 安装 Futhark（只需要工具链）
      - name: Install Futhark
        uses: diku-dk/install-futhark@v1.1.0
        with:
          version: nightly

      # 4. 安装 ISPC
      - name: Install ISPC
        run: |
          sudo apt-get install -y ispc

      # 5. 在指定目录同步 futhark 包
      - name: Futhark pkg sync
        working-directory: ./Material/Extract/futhark
        run: |
          futhark pkg sync

      # 6. 最后运行 Lean Action（它会自动 lake build）
      - name: Build Lean project
        uses: leanprover/lean-action@v1
        env:
          LEAN_CC: clang


